version: '3.8'
services:
  api:
    container_name: holsome-api
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3001
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - api
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    networks:
      - api
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

networks:
  api:
    driver: bridge

volumes:
  pgdata:
    driver: local
